blank_issues_enabled: true
contact_links:
  - name: Hara documentation
    url: https://www.hara-lang.org/docs/start/orientation/
    about: Check the language documentation before filing a general Hara support request here.
